
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action OpenAction;

	private global::Gtk.Action QuitAction;

	private global::Gtk.Action SettingsAction;

	private global::Gtk.Action HideMenuBarAction;

	private global::Gtk.Action HelpAction;

	private global::Gtk.Action AboutAction;

	private global::Gtk.Action DonationsAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Button buttonBack;

	private global::Gtk.Button buttonForward;

	private global::Gtk.Button button4;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Entry entry1;

	private global::Gtk.Button buttonSearch;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Button button_menu;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Button button1;

	private global::Gtk.Button button2;

	private global::Gtk.VBox vbox2;

	private global::Gtk.ScrolledWindow scrolledwindow1;

	private global::Gtk.Notebook notebook1;

	private global::Gtk.Label label1;

	private global::Gtk.HSeparator hseparator1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction, null);
		this.OpenAction = new global::Gtk.Action("OpenAction", global::Mono.Unix.Catalog.GetString("Open"), null, null);
		this.OpenAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Open");
		w1.Add(this.OpenAction, "<Primary>o");
		this.QuitAction = new global::Gtk.Action("QuitAction", global::Mono.Unix.Catalog.GetString("Quit"), null, null);
		this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Quit");
		w1.Add(this.QuitAction, "<Primary>q");
		this.SettingsAction = new global::Gtk.Action("SettingsAction", global::Mono.Unix.Catalog.GetString("Settings"), null, null);
		this.SettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Settings");
		w1.Add(this.SettingsAction, null);
		this.HideMenuBarAction = new global::Gtk.Action("HideMenuBarAction", global::Mono.Unix.Catalog.GetString("Hide menu bar"), null, null);
		this.HideMenuBarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Hide menu bar");
		w1.Add(this.HideMenuBarAction, null);
		this.HelpAction = new global::Gtk.Action("HelpAction", global::Mono.Unix.Catalog.GetString("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Help");
		w1.Add(this.HelpAction, null);
		this.AboutAction = new global::Gtk.Action("AboutAction", global::Mono.Unix.Catalog.GetString("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString("About");
		w1.Add(this.AboutAction, null);
		this.DonationsAction = new global::Gtk.Action("DonationsAction", global::Mono.Unix.Catalog.GetString("Donations"), null, null);
		this.DonationsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Donations");
		w1.Add(this.DonationsAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Greending");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='OpenAction' action='OpenAction'/><menuitem name='QuitAction' action='QuitAction'/></menu><menu name='SettingsAction' action='SettingsAction'><menuitem name='HideMenuBarAction' action='HideMenuBarAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='AboutAction' action='AboutAction'/><menuitem name='DonationsAction' action='DonationsAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add(this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.buttonBack = new global::Gtk.Button();
		this.buttonBack.CanFocus = true;
		this.buttonBack.Name = "buttonBack";
		this.buttonBack.UseUnderline = true;
		this.buttonBack.Label = global::Mono.Unix.Catalog.GetString("←");
		this.hbox2.Add(this.buttonBack);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.buttonBack]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.buttonForward = new global::Gtk.Button();
		this.buttonForward.CanFocus = true;
		this.buttonForward.Name = "buttonForward";
		this.buttonForward.UseUnderline = true;
		this.buttonForward.Label = global::Mono.Unix.Catalog.GetString("→");
		this.hbox2.Add(this.buttonForward);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.buttonForward]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("⟲");
		this.hbox2.Add(this.button4);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button4]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		this.hbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbox2]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.entry1 = new global::Gtk.Entry();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '•';
		this.hbox3.Add(this.entry1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.entry1]));
		w7.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.buttonSearch = new global::Gtk.Button();
		this.buttonSearch.CanFocus = true;
		this.buttonSearch.Name = "buttonSearch";
		this.buttonSearch.UseUnderline = true;
		this.buttonSearch.Label = global::Mono.Unix.Catalog.GetString("🔍");
		this.hbox3.Add(this.buttonSearch);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.buttonSearch]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		this.hbox1.Add(this.hbox3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbox3]));
		w9.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.button_menu = new global::Gtk.Button();
		this.button_menu.CanFocus = true;
		this.button_menu.Name = "button_menu";
		this.button_menu.UseUnderline = true;
		this.button_menu.Label = global::Mono.Unix.Catalog.GetString("⚙");
		this.hbox4.Add(this.button_menu);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.button_menu]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("New");
		this.hbox5.Add(this.button1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.button1]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("Close");
		this.hbox5.Add(this.button2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.button2]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		this.hbox4.Add(this.hbox5);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hbox5]));
		w13.Position = 1;
		this.hbox1.Add(this.hbox4);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbox4]));
		w14.Position = 2;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		global::Gtk.Viewport w16 = new global::Gtk.Viewport();
		w16.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.notebook1 = new global::Gtk.Notebook();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 0;
		// Notebook tab
		global::Gtk.Label w17 = new global::Gtk.Label();
		w17.Visible = true;
		this.notebook1.Add(w17);
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("page1");
		this.notebook1.SetTabLabel(w17, this.label1);
		this.label1.ShowAll();
		w16.Add(this.notebook1);
		this.scrolledwindow1.Add(w16);
		this.vbox2.Add(this.scrolledwindow1);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.scrolledwindow1]));
		w20.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.Name = "hseparator1";
		this.vbox2.Add(this.hseparator1);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hseparator1]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		this.vbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
		w22.Position = 2;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 538;
		this.DefaultHeight = 524;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.OpenAction.Activated += new global::System.EventHandler(this.Open);
		this.QuitAction.Activated += new global::System.EventHandler(this.Quit);
		this.HideMenuBarAction.Activated += new global::System.EventHandler(this.HideMenuBar);
		this.AboutAction.Activated += new global::System.EventHandler(this.About);
		this.DonationsAction.Activated += new global::System.EventHandler(this.Donations);
		this.buttonBack.Clicked += new global::System.EventHandler(this.GoBack);
		this.buttonForward.Clicked += new global::System.EventHandler(this.GoForward);
		this.button4.Clicked += new global::System.EventHandler(this.Reload);
		this.entry1.EditingDone += new global::System.EventHandler(this.OpenURL);
		this.entry1.Activated += new global::System.EventHandler(this.OpenURL);
		this.buttonSearch.Clicked += new global::System.EventHandler(this.OpenURL);
		this.button_menu.Clicked += new global::System.EventHandler(this.OpenMenu);
		this.button1.Clicked += new global::System.EventHandler(this.NewTab);
		this.button2.Clicked += new global::System.EventHandler(this.CloseTab);
		this.notebook1.SwitchPage += new global::Gtk.SwitchPageHandler(this.OnChangeTab);
	}
}
